# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- v2.x

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    platform: 'Any CPU'
    configuration: 'Release'
    clean: true
    msbuildArchitecture: 'x64'
    createLogFile: true
    logFileVerbosity: 'detailed'
