# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- v2.x

stages:
- stage: Build

  variables:
    projectfile: '**/*.$(Agent.JobName).csproj'

  jobs:
  - job: PLC

    pool:
      vmImage: 'windows-latest'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

  - job: WPF
    dependsOn: PLC
#    strategy:
#      maxParallel: 3
#      matrix:
#        WinWPF:
#          PlatformLayer: WPF
#          OSLayer: Windows
#        WinGTK:
#          PlatformLayer: GTK
#          OSLayer: Windows
#        AnyGTK:
#          PlatformLayer: GTK
#          OSLayer: Any
    pool:
      vmImage: 'windows-latest'

    steps:
#    - task: DotNetCoreCLI@2
#      inputs:
#        command: 'restore'
#        projects: '$(projectfile)'
#        feedsToUse: 'select'

    - task: MSBuild@1
      inputs:
        solution: '$(projectfile)'
        msbuildArchitecture: 'x64'
        platform: 'AnyCPU'
        configuration: 'Release'
        clean: true
        logProjectEvents: true
        createLogFile: true
        logFileVerbosity: 'detailed'

#    - task: VSBuild@1
#      inputs:
#        solution: '**\*.sln'
#        vsVersion: '16.0'
#        platform: 'Any CPU'
#        configuration: 'Release'
#        clean: true
#        msbuildArchitecture: 'x64'
#        createLogFile: true
#        logFileVerbosity: 'detailed'
