# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- v2.x

stages:
- stage: Build

#  variables:
#    projectfile: '**/*.$(Agent.JobName).csproj'

  jobs:
  - job:

    strategy:
      maxParallel: 2
      matrix:
        WinWPF:
          PlatformLayer: WPF
          OSLayer: Windows
#        WinGTK:
#          PlatformLayer: GTK
#          OSLayer: Windows
        AnyGTK:
          PlatformLayer: GTK
          OSLayer: Any
    pool:
      vmImage: 'windows-latest'

  variables:
    projectfile: '**/*.$(PlatformLayer).csproj'

    steps:

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

    - task: MSBuild@1
      inputs:
        solution: '$(projectfile)'
        msbuildArchitecture: 'x64'
        platform: 'AnyCPU'
        configuration: 'Release'
        clean: true
        logProjectEvents: true
        createLogFile: true
        logFileVerbosity: 'detailed'
